#!/bin/bash

crystal build --no-debug --release -p src/ng-attendance.cr

elm make --optimize src/Main.elm --output public/elm.js
uglifyjs public/elm.js --compress 'pure_funcs=[F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9],pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output public/elm.min.js

cd public/css
cleancss -O2 fonts.css normalize.css skeleton.css application.css > frc862.min.css



