INSERT INTO users (name, email, student_number) VALUES ('Rick Armstrong', 'rocco@jast-crooks.name', '507701686');
INSERT INTO users (name, email, student_number) VALUES ('Hassan DuBuque', 'sanjuana.kunde@shanahan.info', '075416366');
INSERT INTO users (name, email, student_number) VALUES ('Pres. Augustus Connelly', 'collene@kertzmann-senger.org', '610300220');
INSERT INTO users (name, email, student_number) VALUES ('Tilda Mitchell', 'tiffany@dubuque.io', '656781594');
INSERT INTO users (name, email, student_number) VALUES ('Vince Jast', 'curtis@johns.biz', '673875851');
INSERT INTO users (name, email, student_number) VALUES ('Sandie Kub I', 'sharri_kiehn@harris.co', '722879336');
INSERT INTO users (name, email, student_number) VALUES ('Rolf DuBuque', 'freeman@fritsch.com', '363126992');
INSERT INTO users (name, email, student_number) VALUES ('Rep. Ike Metz', 'elton.jaskolski@sporer.info', '639559104');
INSERT INTO users (name, email, student_number) VALUES ('Moises Oberbrunner', 'lakeesha@miller.info', '827755399');
INSERT INTO users (name, email, student_number) VALUES ('Kandice Zulauf', 'anglea_mante@von-bernier.co', '690640112');
INSERT INTO users (name, email, student_number) VALUES ('Inell Cormier', 'leighann@moen-mante.co', '582881518');
INSERT INTO users (name, email, student_number) VALUES ('Trudy Ernser Sr.', 'patricia_mueller@jacobson-murray.biz', '124388877');
INSERT INTO users (name, email, student_number) VALUES ('Sanjuana Dooley', 'lucina.kshlerin@swift.name', '454463757');
INSERT INTO users (name, email, student_number) VALUES ('Allan Dare', 'trinidad@erdman.biz', '457714734');
INSERT INTO users (name, email, student_number) VALUES ('Man King', 'douglas.terry@von.biz', '325820462');
INSERT INTO users (name, email, student_number) VALUES ('Randell Schimmel', 'charisse@fahey-jacobi.com', '830771378');
INSERT INTO users (name, email, student_number) VALUES ('Ms. Vance Ortiz', 'america.collins@schimmel.com', '114283994');
INSERT INTO users (name, email, student_number) VALUES ('Josue Sauer', 'abdul_mcdermott@harris.com', '064419016');
INSERT INTO users (name, email, student_number) VALUES ('Aimee Stehr', 'veola@hamill-christiansen.biz', '895995656');
INSERT INTO users (name, email, student_number) VALUES ('Ellen Ernser IV', 'quiana.mclaughlin@becker.net', '640966404');
INSERT INTO users (name, email, student_number) VALUES ('Sen. Jeromy Effertz', 'kendall@torphy.biz', '439193947');
INSERT INTO users (name, email, student_number) VALUES ('Diego Schulist IV', 'curtis.kozey@friesen.name', '035214024');
INSERT INTO users (name, email, student_number) VALUES ('Diego Goldner', 'stefan.koelpin@volkman.co', '029267174');
INSERT INTO users (name, email, student_number) VALUES ('Prof. Sid Haag', 'dion@sipes.name', '010655412');
INSERT INTO users (name, email, student_number) VALUES ('Casey Murazik', 'adela_schroeder@aufderhar-howell.name', '292989925');
INSERT INTO users (name, email, student_number) VALUES ('Darnell Renner', 'damon.lind@collins-klein.info', '195986205');
INSERT INTO users (name, email, student_number) VALUES ('Victor McKenzie', 'numbers.schamberger@cartwright.io', '286491349');
INSERT INTO users (name, email, student_number) VALUES ('Soila Denesik', 'stuart@williamson.info', '892038879');
INSERT INTO users (name, email, student_number) VALUES ('Leena Klein', 'fiona_keebler@simonis.net', '342875622');
INSERT INTO users (name, email, student_number) VALUES ('Phylicia Legros', 'kelle@dickinson.name', '246122652');
INSERT INTO users (name, email, student_number) VALUES ('Wesley Gusikowski', 'cleveland.jakubowski@volkman.co', '426272923');
INSERT INTO users (name, email, student_number) VALUES ('Mrs. Katharyn Collins', 'cory@schmitt.biz', '043954402');
INSERT INTO users (name, email, student_number) VALUES ('Berry Gislason', 'katherine_boehm@kshlerin.biz', '516206103');
INSERT INTO users (name, email, student_number) VALUES ('Mallie Bailey VM', 'darren_schowalter@rolfson.biz', '215852676');
INSERT INTO users (name, email, student_number) VALUES ('Micah Witting', 'gustavo@wiegand.org', '226604073');
INSERT INTO users (name, email, student_number) VALUES ('Terrilyn Botsford', 'aron@bergstrom-hyatt.co', '097328044');
INSERT INTO users (name, email, student_number) VALUES ('Shannon Hegmann VM', 'truman@stehr.info', '257621965');
INSERT INTO users (name, email, student_number) VALUES ('Dinah Christiansen Sr.', 'lyman@durgan-kshlerin.io', '541484533');
INSERT INTO users (name, email, student_number) VALUES ('Maurice Lang', 'giuseppe.weissnat@bosco.com', '103110455');
INSERT INTO users (name, email, student_number) VALUES ('Clarence Hammes', 'werner@boyle-mitchell.io', '784427542');
INSERT INTO users (name, email, student_number) VALUES ('Elden Rempel', 'carlee@trantow-bergnaum.name', '297111113');
INSERT INTO users (name, email, student_number) VALUES ('Max Rohan', 'numbers@robel-lemke.org', '418040510');
INSERT INTO users (name, email, student_number) VALUES ('Rev. Mohamed Hackett', 'lakita_haag@jacobs.name', '315717672');
INSERT INTO users (name, email, student_number) VALUES ('Nigel Ziemann II', 'benedict@hagenes-schiller.org', '164276098');
INSERT INTO users (name, email, student_number) VALUES ('Chi Grant', 'bruno.hahn@hermiston-littel.biz', '800064428');
INSERT INTO users (name, email, student_number) VALUES ('Seth Kuvalis', 'jon_labadie@jaskolski-doyle.org', '517159124');
INSERT INTO users (name, email, student_number) VALUES ('Kelvin Crist DO', 'alex.cummerata@schroeder-aufderhar.io', '541021263');
INSERT INTO users (name, email, student_number) VALUES ('Pat Lebsack JD', 'adolph@kozey-jaskolski.biz', '651931726');
INSERT INTO users (name, email, student_number) VALUES ('Starla Abernathy', 'raymond_kuvalis@boyle.info', '569663087');
INSERT INTO users (name, email, student_number) VALUES ('Pres. Brenton Bergnaum', 'lahoma.kuhic@powlowski.net', '346139219');
INSERT INTO users (name, email, student_number) VALUES ('Conchita Buckridge', 'genoveva@ortiz-kessler.biz', '060442701');
INSERT INTO users (name, email, student_number) VALUES ('Tawana Ritchie', 'vi_hegmann@wilkinson.io', '031341562');
INSERT INTO users (name, email, student_number) VALUES ('Melissa Roberts', 'marinda@williamson.name', '891785789');
INSERT INTO users (name, email, student_number) VALUES ('Oren Moore DO', 'mattie_nienow@legros.biz', '059588516');
INSERT INTO users (name, email, student_number) VALUES ('Pres. German Cassin', 'giuseppe_keeling@lynch.name', '390601155');
INSERT INTO users (name, email, student_number) VALUES ('Arlie Ryan', 'thi@hansen.name', '372905674');
INSERT INTO users (name, email, student_number) VALUES ('Gaye Medhurst', 'arleen.quigley@mcglynn.name', '763627630');
INSERT INTO users (name, email, student_number) VALUES ('Kacy Cormier VM', 'madalyn_breitenberg@larson.biz', '466373634');
INSERT INTO users (name, email, student_number) VALUES ('Joel Dietrich II', 'hugo@koelpin-price.co', '305046056');
INSERT INTO users (name, email, student_number) VALUES ('Rosaline Swaniawski II', 'mable_hahn@williamson.org', '045213087');
INSERT INTO users (name, email, student_number) VALUES ('Delorse Douglas DDS', 'edmundo_herman@frami-rempel.co', '812494800');
INSERT INTO users (name, email, student_number) VALUES ('Melaine Koelpin', 'fidela@hayes-mante.name', '517356610');
INSERT INTO users (name, email, student_number) VALUES ('Jeane Baumbach', 'amina_boehm@jacobson.name', '107398188');
INSERT INTO users (name, email, student_number) VALUES ('Micheline Nienow DVM', 'mikki.baumbach@rau-cremin.org', '431876138');
INSERT INTO users (name, email, student_number) VALUES ('Desmond Wisoky', 'wanita_kutch@simonis.org', '710701814');
INSERT INTO users (name, email, student_number) VALUES ('Katherin King', 'phylis_bauch@trantow.net', '891848434');
INSERT INTO users (name, email, student_number) VALUES ('Noble Raynor', 'dewitt.satterfield@olson.org', '021270105');
INSERT INTO users (name, email, student_number) VALUES ('Eduardo Wisoky', 'kittie@farrell.net', '687246414');
INSERT INTO users (name, email, student_number) VALUES ('Gwenda Emmerich', 'ferdinand@durgan.io', '255106252');
INSERT INTO users (name, email, student_number) VALUES ('Mitch Weissnat', 'francene@hane-hayes.co', '438672507');
INSERT INTO users (name, email, student_number) VALUES ('Jeramy Rippin', 'merle@senger.net', '156427194');
INSERT INTO users (name, email, student_number) VALUES ('Erick Beier DC', 'merrie@willms.com', '138468335');
INSERT INTO users (name, email, student_number) VALUES ('Nathanael Howe', 'aileen@rutherford-crooks.com', '758354967');
INSERT INTO users (name, email, student_number) VALUES ('Nohemi Bayer', 'brendan@feil-stokes.co', '782267625');
INSERT INTO users (name, email, student_number) VALUES ('Man DuBuque', 'florrie@crona-wilderman.co', '147451570');
INSERT INTO users (name, email, student_number) VALUES ('Adrian Collins', 'donna_mitchell@rutherford-connelly.biz', '519986620');
INSERT INTO users (name, email, student_number) VALUES ('Janessa Turner', 'carey@larkin-treutel.co', '177513368');
INSERT INTO users (name, email, student_number) VALUES ('Virgie Brekke', 'selma.boyer@johnston.org', '453033937');
INSERT INTO users (name, email, student_number) VALUES ('Ms. Melisa Christiansen', 'eve_ortiz@little.co', '247084287');
INSERT INTO users (name, email, student_number) VALUES ('Rev. Reynalda Kutch', 'richard@murazik.biz', '861241739');
INSERT INTO users (name, email, student_number) VALUES ('Soraya Mayert', 'angelo.rutherford@hoppe-hudson.co', '296151649');
INSERT INTO users (name, email, student_number) VALUES ('Meggan Rice', 'mack@nicolas.io', '220275272');
INSERT INTO users (name, email, student_number) VALUES ('Mohammad Simonis', 'candance_watsica@volkman.co', '764123777');
INSERT INTO users (name, email, student_number) VALUES ('Pres. Rosy Medhurst', 'milda_howe@stokes.name', '885946540');
INSERT INTO users (name, email, student_number) VALUES ('Rev. Karl Schmeler', 'ed_fritsch@larson.biz', '807924457');
INSERT INTO users (name, email, student_number) VALUES ('Frank Cummings', 'porfirio@metz-keebler.biz', '341418242');
INSERT INTO users (name, email, student_number) VALUES ('Wesley Wintheiser', 'keneth@fahey.org', '866901891');
INSERT INTO users (name, email, student_number) VALUES ('Leoma Turner', 'bert.howell@macejkovic.info', '885246222');
INSERT INTO users (name, email, student_number) VALUES ('Elliott Sauer VM', 'ernestina_altenwerth@mcdermott.org', '828619923');
INSERT INTO users (name, email, student_number) VALUES ('Yu Marks MD', 'ester.anderson@rath-cartwright.com', '002338054');
INSERT INTO users (name, email, student_number) VALUES ('Isaiah Tillman', 'genevieve@lehner.org', '322814779');
INSERT INTO users (name, email, student_number) VALUES ('Alton Schaden', 'claris@connelly-mueller.net', '213071720');
INSERT INTO users (name, email, student_number) VALUES ('Ludivina Douglas', 'brigette@kertzmann.net', '672579587');
INSERT INTO users (name, email, student_number) VALUES ('Thomasine Emard', 'mervin.zulauf@kozey.org', '291246363');
INSERT INTO users (name, email, student_number) VALUES ('Debbi Lubowitz', 'salvador@labadie.biz', '312256633');
INSERT INTO users (name, email, student_number) VALUES ('Maire Rau', 'august@jerde-hammes.co', '362976715');
INSERT INTO users (name, email, student_number) VALUES ('Mrs. Velva Thiel', 'hank.adams@parisian.name', '357538993');
INSERT INTO users (name, email, student_number) VALUES ('Breann Hilpert', 'earnest@kilback-beer.io', '039581335');
INSERT INTO users (name, email, student_number) VALUES ('Keneth Stoltenberg', 'cathern@conn-nikolaus.biz', '606793953');
INSERT INTO users (name, email, student_number) VALUES ('Dalene Schowalter', 'bart@jones.co', '530771949');
INSERT INTO users (name, email, student_number) VALUES ('Eloy McGlynn', 'alva.schmitt@parisian-bruen.info', '333557264');
INSERT INTO users (name, email, student_number) VALUES ('Ms. Jeff Howe', 'otha_little@farrell.co', '707840843');
INSERT INTO users (name, email, student_number) VALUES ('Alfred Simonis', 'jake@gutkowski-hegmann.co', '857518780');
INSERT INTO users (name, email, student_number) VALUES ('Francisco Kub LLD', 'domitila@quitzon.org', '088956555');
INSERT INTO users (name, email, student_number) VALUES ('Nickolas Romaguera', 'shera.runolfsson@reichel.net', '366801347');
INSERT INTO users (name, email, student_number) VALUES ('Yee Yost DVM', 'emilio.harris@stroman.co', '411495545');
INSERT INTO users (name, email, student_number) VALUES ('Maritza Corkery', 'ricki@conroy.io', '883155136');
INSERT INTO users (name, email, student_number) VALUES ('Andreas Ruecker', 'pat@carter.net', '313266655');
INSERT INTO users (name, email, student_number) VALUES ('Bryanna Koss', 'lucius@fritsch-kutch.com', '747838495');
INSERT INTO users (name, email, student_number) VALUES ('Filiberto Satterfield', 'michel.bechtelar@beatty-thiel.co', '456746585');
INSERT INTO users (name, email, student_number) VALUES ('Miss Lida Mohr', 'astrid@padberg-nikolaus.name', '258595246');
INSERT INTO users (name, email, student_number) VALUES ('Gale Gislason', 'sonja@bode.org', '641204409');
INSERT INTO users (name, email, student_number) VALUES ('Darnell Carter', 'jere.mann@kautzer.info', '854123509');
INSERT INTO users (name, email, student_number) VALUES ('Lani Gleason Ret.', 'madie@kuphal-tromp.net', '749192459');
INSERT INTO users (name, email, student_number) VALUES ('Shane Hand', 'julieta@turcotte.io', '179774881');
INSERT INTO users (name, email, student_number) VALUES ('Lindsey Rau', 'katherine_champlin@dibbert.org', '648396652');
INSERT INTO users (name, email, student_number) VALUES ('Alda Beier Ret.', 'noemi.lubowitz@hansen-runolfsson.com', '056202879');
INSERT INTO users (name, email, student_number) VALUES ('Miss Loren Fahey', 'christian@muller.biz', '140419485');
INSERT INTO users (name, email, student_number) VALUES ('Amb. Marcie Hessel', 'suk.murray@jakubowski.name', '586037592');
INSERT INTO users (name, email, student_number) VALUES ('Ulysses Brakus', 'carmon_reichert@gibson-kihn.net', '789662712');
INSERT INTO users (name, email, student_number) VALUES ('Arnoldo Farrell', 'kathryn_pacocha@champlin.io', '783560214');
INSERT INTO users (name, email, student_number) VALUES ('Kizzy Considine', 'tenesha_glover@stiedemann.biz', '593716329');
INSERT INTO users (name, email, student_number) VALUES ('Kevin Ratke', 'freddie@adams.info', '203072068');
INSERT INTO users (name, email, student_number) VALUES ('Monty Blanda VM', 'marisela@mueller.org', '158597449');
INSERT INTO users (name, email, student_number) VALUES ('Gaye Murphy', 'jannette.wolf@rutherford-beier.co', '806926365');
INSERT INTO users (name, email, student_number) VALUES ('Stevie Kilback', 'reanna.gislason@brekke.com', '723454209');
INSERT INTO users (name, email, student_number) VALUES ('Mr. Ward Dickinson', 'lucius.dietrich@grant.com', '823500471');
INSERT INTO users (name, email, student_number) VALUES ('Nelson Koch', 'hope@pouros-oconnell.biz', '231902664');
INSERT INTO users (name, email, student_number) VALUES ('Alfonzo Funk', 'tanja@kuhlman.biz', '623270506');
INSERT INTO users (name, email, student_number) VALUES ('Elana Kuhn CPA', 'larhonda_gorczany@huel.info', '437853263');
INSERT INTO users (name, email, student_number) VALUES ('Howard Kertzmann', 'elijah@mosciski.net', '078339771');
INSERT INTO users (name, email, student_number) VALUES ('Elwanda Abbott', 'fritz_boyle@grant-welch.co', '748803898');
INSERT INTO users (name, email, student_number) VALUES ('Dan Kling', 'paul.romaguera@strosin-steuber.info', '017277615');
INSERT INTO users (name, email, student_number) VALUES ('Edwin Daniel', 'shae@dicki.org', '579752760');
INSERT INTO users (name, email, student_number) VALUES ('Noble Price', 'joseph@runte-ziemann.info', '433642573');
INSERT INTO users (name, email, student_number) VALUES ('Horacio Huels PhD', 'veronica_fisher@mills.io', '801595483');
INSERT INTO users (name, email, student_number) VALUES ('Fredric Johns', 'ariel_goodwin@smith.net', '685535177');
INSERT INTO users (name, email, student_number) VALUES ('Amb. Tony Leuschke', 'cherrie@white-willms.org', '824290661');
INSERT INTO users (name, email, student_number) VALUES ('Omer Rogahn', 'armand_wilderman@bartell-hand.info', '739786969');
INSERT INTO users (name, email, student_number) VALUES ('Narcisa Schuppe Sr.', 'melinda.howell@rowe-gleichner.org', '582724022');
INSERT INTO users (name, email, student_number) VALUES ('Rev. Giovanni Bechtelar', 'donny@watsica.name', '117398751');
INSERT INTO users (name, email, student_number) VALUES ('Na Lowe', 'santiago@pollich.co', '037235118');
INSERT INTO users (name, email, student_number) VALUES ('Elma Conroy', 'dania@jakubowski.com', '271943481');
INSERT INTO users (name, email, student_number) VALUES ('Ms. Tomas Reynolds', 'maribeth@maggio-corwin.name', '813314317');
INSERT INTO users (name, email, student_number) VALUES ('Ellena Bins', 'bret@schowalter.biz', '024187666');
INSERT INTO users (name, email, student_number) VALUES ('Shani Keeling', 'danny_towne@trantow-luettgen.org', '844623266');
INSERT INTO users (name, email, student_number) VALUES ('Gale Corwin Ret.', 'jordon@langworth.co', '787148862');
INSERT INTO users (name, email, student_number) VALUES ('Jeffery Dickinson', 'carrol_schaefer@moore.co', '698814265');
INSERT INTO users (name, email, student_number) VALUES ('Luther Morissette', 'kelvin_harvey@welch.com', '471814321');
INSERT INTO users (name, email, student_number) VALUES ('Arnold Murazik', 'carolynn.kohler@tillman.net', '425117231');
INSERT INTO users (name, email, student_number) VALUES ('Amado Rolfson Sr.', 'delisa@ondricka-dubuque.net', '071920266');
INSERT INTO users (name, email, student_number) VALUES ('Harrison Predovic', 'corina@botsford-hammes.io', '646746160');
INSERT INTO users (name, email, student_number) VALUES ('Lura Beatty', 'damian@sauer-lowe.info', '521569630');
INSERT INTO users (name, email, student_number) VALUES ('Howard Wiegand Esq.', 'rory_oconner@renner.co', '543614897');
INSERT INTO users (name, email, student_number) VALUES ('Geraldo Lehner VM', 'madelyn@turner.biz', '618745815');
INSERT INTO users (name, email, student_number) VALUES ('Rev. Wyatt Raynor', 'cleta_sawayn@daniel-vandervort.io', '725123614');
INSERT INTO users (name, email, student_number) VALUES ('Janiece Bartell', 'jeromy@oconnell.net', '459181150');
INSERT INTO users (name, email, student_number) VALUES ('Tim Pacocha', 'stefany@hammes.info', '111643659');
INSERT INTO users (name, email, student_number) VALUES ('Jarrod Corwin', 'loralee@schamberger.com', '401963845');
INSERT INTO users (name, email, student_number) VALUES ('Isadora Hand IV', 'ebony@kautzer.org', '774181561');
INSERT INTO users (name, email, student_number) VALUES ('Josephine Spinka', 'leland.lueilwitz@mertz-wiegand.net', '407760880');
INSERT INTO users (name, email, student_number) VALUES ('Dr. Fletcher Yost', 'dawn@schinner.biz', '047019009');
INSERT INTO users (name, email, student_number) VALUES ('Ryan Fadel JD', 'ashley@lebsack.co', '751500749');
INSERT INTO users (name, email, student_number) VALUES ('Dwayne Thiel', 'andres@crist.org', '024670258');
INSERT INTO users (name, email, student_number) VALUES ('Danial Herzog', 'micki@oberbrunner.net', '151019863');
INSERT INTO users (name, email, student_number) VALUES ('Sheri Morar', 'adrian_deckow@mitchell.biz', '763712649');
INSERT INTO users (name, email, student_number) VALUES ('Josphine Lynch Esq.', 'lyndsey@purdy.co', '890937913');
INSERT INTO users (name, email, student_number) VALUES ('Elvie Kunze', 'madison.hilll@beatty.name', '099813817');
INSERT INTO users (name, email, student_number) VALUES ('Alphonse Cremin', 'genaro@kohler.net', '357137575');
INSERT INTO users (name, email, student_number) VALUES ('Pres. Richard Beier', 'kacey@gleichner.io', '817032017');
INSERT INTO users (name, email, student_number) VALUES ('Javier Kunde Sr.', 'mauricio@morissette.name', '017576626');
INSERT INTO users (name, email, student_number) VALUES ('Alec Hickle', 'leila@kirlin.net', '574823699');
INSERT INTO users (name, email, student_number) VALUES ('Amb. Mauricio Lind', 'cesar@gottlieb.io', '814151020');
INSERT INTO users (name, email, student_number) VALUES ('Terrance Bergstrom', 'amanda@hyatt-bailey.com', '559602343');
INSERT INTO users (name, email, student_number) VALUES ('Mrs. Reatha Quitzon', 'evan@hegmann-renner.co', '692083246');
INSERT INTO users (name, email, student_number) VALUES ('Dr. Norris Koepp', 'estela_ryan@douglas-barton.org', '074367226');
INSERT INTO users (name, email, student_number) VALUES ('Duane Bailey', 'mui.fritsch@hagenes-cassin.io', '847722358');
INSERT INTO users (name, email, student_number) VALUES ('Bruno Lakin', 'bennett@gorczany.biz', '717391221');
INSERT INTO users (name, email, student_number) VALUES ('Valentin Purdy', 'roscoe_turner@walter.io', '069978581');
INSERT INTO users (name, email, student_number) VALUES ('Teddy Goodwin', 'nicki.ward@weber.co', '723318464');
INSERT INTO users (name, email, student_number) VALUES ('Leslee Swaniawski', 'wilfredo.cormier@murphy.name', '533612501');
INSERT INTO users (name, email, student_number) VALUES ('Lindsay Greenfelder', 'jeanene@nienow-wilkinson.io', '780532813');
INSERT INTO users (name, email, student_number) VALUES ('Prof. Marty Koch', 'margaretta@johns.net', '774823074');
INSERT INTO users (name, email, student_number) VALUES ('Bernetta Lind Ret.', 'scott@glover.com', '236906378');
INSERT INTO users (name, email, student_number) VALUES ('Larissa Heidenreich JD', 'bianca@metz-hackett.co', '294828879');
INSERT INTO users (name, email, student_number) VALUES ('Jackie Leuschke', 'lindsay.mohr@littel.net', '830211838');
INSERT INTO users (name, email, student_number) VALUES ('Del Veum', 'eliz.mertz@vandervort-wolff.info', '465690410');
INSERT INTO users (name, email, student_number) VALUES ('Wilfred Glover', 'rodger.osinski@wolff.io', '708603718');
INSERT INTO users (name, email, student_number) VALUES ('Carisa Turner', 'sadye@casper.info', '546618026');
INSERT INTO users (name, email, student_number) VALUES ('Blake Mosciski IV', 'amina@christiansen-torp.com', '500890841');
INSERT INTO users (name, email, student_number) VALUES ('Lloyd Skiles', 'cassaundra@jacobi.biz', '763392024');
INSERT INTO users (name, email, student_number) VALUES ('Anton Kreiger', 'karri_funk@goldner.com', '265686735');
INSERT INTO users (name, email, student_number) VALUES ('Dr. Kip Schiller', 'clarence_konopelski@botsford.org', '603705356');
INSERT INTO users (name, email, student_number) VALUES ('Dee Hilpert', 'maren@weissnat.co', '580129231');
INSERT INTO users (name, email, student_number) VALUES ('Enoch Russel', 'nakesha_medhurst@wintheiser.co', '852299338');
INSERT INTO users (name, email, student_number) VALUES ('Quinn Crooks', 'johnathan_lakin@fay.io', '238619677');
INSERT INTO users (name, email, student_number) VALUES ('Jamey Steuber', 'leila@ward.org', '719150315');
INSERT INTO users (name, email, student_number) VALUES ('Parker Williamson CPA', 'ernie@bechtelar.org', '677274136');
INSERT INTO users (name, email, student_number) VALUES ('Wyatt Cormier IV', 'fausto@kunde.name', '200559423');
INSERT INTO users (name, email, student_number) VALUES ('Lonny Pfeffer', 'warner@nienow-williamson.biz', '731533275');
